from .core.config import (
    DatabaseProjectConfig,
    register_database,
    register_database_from_env,
    get_database_config,
    get_connection_string,
    get_manager_config,
    get_code_config,
    get_schema_builder_overrides,
    get_all_database_project_names,
    get_database_alias,
    get_all_database_projects_redacted,
)

from .core.extended import BaseManager, BaseDTO
from .core.model_view import ModelView
from .core.base import Model
from .core.registry import model_registry
from .core.types import (
    AggregateResult,
    AllRelatedResults,
    ForeignKeyResults,
    InverseForeignKeyResults,
    ManyToManyResults,
    UpdateResult,
)
from .core.fields import (
    Field,
    CharField,
    EnumField,
    DateField,
    TextField,
    IntegerField,
    FloatField,
    BooleanField,
    DateTimeField,
    TimeField,
    UUIDField,
    JSONField,
    DecimalField,
    BigIntegerField,
    SmallIntegerField,
    JSONBField,
    UUIDArrayField,
    JSONBArrayField,
    ForeignKey,
    IPAddressField,
    ArrayField,
    TextArrayField,
    IntegerArrayField,
    BooleanArrayField,
    BinaryField,
    TimeDeltaField,
    IPNetworkField,
    MacAddressField,
    HStoreField,
    PointField,
    MoneyField,
    PrimitiveArrayField,
    VersionField,
    VectorField,
)
from .core.relations import ManyToManyField
from .core.expressions import (
    F,
    Expression,
    Q,
    OuterRef,
    Subquery,
    Exists,
    Func,
    Coalesce,
    Lower,
    Upper,
    Length,
    Trim,
    Now,
    Concat,
    Greatest,
    Least,
    Abs,
    Round,
    Cast,
    Extract,
    DateTrunc,
    Sum,
    Avg,
    Min,
    Max,
    Count,
    StdDev,
    Variance,
    # Window functions
    Window,
    RowNumber,
    Rank,
    DenseRank,
    Lag,
    Lead,
    FirstValue,
    LastValue,
    NthValue,
    Ntile,
    CumeDist,
    PercentRank,
    # CTEs
    CTE,
    # Vector search
    VectorDistance,
    VECTOR_METRICS,
)
from .core.paginator import Paginator, Page
from .core.signals import (
    Signal,
    pre_create,
    post_create,
    pre_save,
    post_save,
    pre_delete,
    post_delete,
)
from .core.transaction import transaction
from .exceptions import OptimisticLockError
from .migrations import (
    MigrationDB,
    MigrationLoader,
    MigrationState,
    MigrationExecutor,
    DDLGenerator,
    IndexDef,
    SchemaDiff,
    TableFilter,
    makemigrations,
    migrate,
    rollback,
    status as migration_status,
    create_empty,
    migrate_and_rebuild,
)

__all__ = [
    "DatabaseProjectConfig",
    "register_database",
    "register_database_from_env",
    "get_database_config",
    "get_connection_string",
    "get_manager_config",
    "get_code_config",
    "get_all_database_project_names",
    "get_default_code_config",
    "BaseManager",
    "BaseDTO",
    "ModelView",
    "Model",
    # Typed result containers
    "AggregateResult",
    "AllRelatedResults",
    "ForeignKeyResults",
    "InverseForeignKeyResults",
    "ManyToManyResults",
    "UpdateResult",
    "model_registry",
    "Field",
    "CharField",
    "EnumField",
    "DateField",
    "TextField",
    "IntegerField",
    "FloatField",
    "BooleanField",
    "DateTimeField",
    "TimeField",
    "UUIDField",
    "JSONField",
    "DecimalField",
    "BigIntegerField",
    "SmallIntegerField",
    "JSONBField",
    "UUIDArrayField",
    "JSONBArrayField",
    "ForeignKey",
    "ManyToManyField",
    # Expressions
    "F",
    "Expression",
    "Q",
    "OuterRef",
    "Subquery",
    "Exists",
    "Func",
    "Coalesce",
    "Lower",
    "Upper",
    "Length",
    "Trim",
    "Now",
    "Concat",
    "Greatest",
    "Least",
    "Abs",
    "Round",
    "Cast",
    "Extract",
    "DateTrunc",
    "Sum",
    "Avg",
    "Min",
    "Max",
    "Count",
    "StdDev",
    "Variance",
    # Window functions
    "Window",
    "RowNumber",
    "Rank",
    "DenseRank",
    "Lag",
    "Lead",
    "FirstValue",
    "LastValue",
    "NthValue",
    "Ntile",
    "CumeDist",
    "PercentRank",
    # CTEs
    "CTE",
    # Vector search
    "VectorField",
    "VectorDistance",
    "VECTOR_METRICS",
    # Paginator
    "Paginator",
    "Page",
    # Fields
    "VersionField",
    # Exceptions
    "OptimisticLockError",
    # Signals
    "Signal",
    "pre_create",
    "post_create",
    "pre_save",
    "post_save",
    "pre_delete",
    "post_delete",
    # Transactions
    "transaction",
    "IPAddressField",
    "ArrayField",
    "TextArrayField",
    "IntegerArrayField",
    "BooleanArrayField",
    "BinaryField",
    "TimeDeltaField",
    "IPNetworkField",
    "MacAddressField",
    "HStoreField",
    "PointField",
    "MoneyField",
    "PrimitiveArrayField",
    "get_schema_builder_overrides",
    "get_database_alias",
    "get_all_database_projects_redacted",
    "MigrationDB",
    "MigrationLoader",
    "MigrationState",
    "MigrationExecutor",
    "DDLGenerator",
    "IndexDef",
    "SchemaDiff",
    "TableFilter",
    "makemigrations",
    "migrate",
    "migration_status",
    "create_empty",
    "rollback",
    "migrate_and_rebuild",
]
