from .core.config import (
    DatabaseProjectConfig,
    register_database,
    register_database_from_env,
    get_database_config,
    get_connection_string,
    get_manager_config,
    get_code_config,
    get_schema_builder_overrides,
    get_all_database_project_names,
    get_database_alias,
    get_all_database_projects_redacted,
)

from .core.extended import BaseManager
from .core.model_dto import BaseDTO
from .core.model_view import ModelView
from .core.base import Model
from .core.registry import model_registry
from .core.types import (
    AggregateResult,
    AllRelatedResults,
    ForeignKeyResults,
    InverseForeignKeyResults,
    ManyToManyResults,
    UpdateResult,
    ModelT,
)
from .core.fields import (
    Field,
    CharField,
    EnumField,
    DateField,
    TextField,
    IntegerField,
    FloatField,
    BooleanField,
    DateTimeField,
    TimeField,
    UUIDField,
    JSONField,
    DecimalField,
    BigIntegerField,
    SmallIntegerField,
    JSONBField,
    UUIDArrayField,
    JSONBArrayField,
    ForeignKey,
    IPAddressField,
    ArrayField,
    TextArrayField,
    IntegerArrayField,
    BooleanArrayField,
    BinaryField,
    TimeDeltaField,
    IPNetworkField,
    MacAddressField,
    HStoreField,
    PointField,
    MoneyField,
    PrimitiveArrayField,
    VersionField,
    VectorField,
    EmailField,
    SlugField,
    FileField,
    ImageField,
    CITextField,
    CompositeField,
    RangeField,
    DecimalArrayField,
    DateArrayField,
    TimeArrayField,
    IPv4Field,
    IPv6Field,
    HStoreArrayField,
    IPNetworkArrayField,
    IPv6ArrayField,
)
from .core.relations import ManyToManyField
from .core.expressions import (
    F,
    Expression,
    Q,
    OuterRef,
    Subquery,
    Exists,
    Func,
    Aggregate,
    Coalesce,
    Lower,
    Upper,
    Length,
    Trim,
    Now,
    Concat,
    Greatest,
    Least,
    Abs,
    Round,
    Cast,
    Extract,
    DateTrunc,
    Sum,
    Avg,
    Min,
    Max,
    Count,
    StdDev,
    Variance,
    # Window functions
    Window,
    RowNumber,
    Rank,
    DenseRank,
    Lag,
    Lead,
    FirstValue,
    LastValue,
    NthValue,
    Ntile,
    CumeDist,
    PercentRank,
    # CTEs
    CTE,
    # Vector search
    VectorDistance,
    VECTOR_METRICS,
)
from .core.paginator import Paginator, Page
from .core.signals import (
    Signal,
    pre_create,
    post_create,
    pre_save,
    post_save,
    pre_delete,
    post_delete,
)
from .core.transaction import transaction
from .exceptions import (
    ORMException,
    ValidationError,
    QueryError,
    DoesNotExist,
    MultipleObjectsReturned,
    DatabaseError,
    ConnectionError,
    IntegrityError,
    TransactionError,
    ConfigurationError,
    CacheError,
    StateError,
    RelationshipError,
    AdapterError,
    FieldError,
    MigrationError,
    ParameterError,
    UnknownDatabaseError,
    OptimisticLockError,
)
from .state import CachePolicy, StateManager
from .query.builder import QueryBuilder
from .migrations import (
    MigrationDB,
    MigrationLoader,
    MigrationState,
    MigrationExecutor,
    DDLGenerator,
    IndexDef,
    SchemaDiff,
    TableFilter,
    makemigrations,
    migrate,
    rollback,
    status as migration_status,
    create_empty,
    migrate_and_rebuild,
)

__all__ = [
    # ── Configuration ──────────────────────────────────────────────────────────
    "DatabaseProjectConfig",
    "register_database",
    "register_database_from_env",
    "get_database_config",
    "get_connection_string",
    "get_manager_config",
    "get_code_config",
    "get_schema_builder_overrides",
    "get_all_database_project_names",
    "get_database_alias",
    "get_all_database_projects_redacted",
    # ── Core model layer ───────────────────────────────────────────────────────
    "Model",
    "BaseManager",
    "BaseDTO",
    "ModelView",
    "model_registry",
    # ── Query API ─────────────────────────────────────────────────────────────
    "QueryBuilder",
    # ── Typed result containers ────────────────────────────────────────────────
    "AggregateResult",
    "AllRelatedResults",
    "ForeignKeyResults",
    "InverseForeignKeyResults",
    "ManyToManyResults",
    "UpdateResult",
    # ── TypeVars (useful for generic annotations in downstream code) ───────────
    "ModelT",
    # ── Fields ────────────────────────────────────────────────────────────────
    "Field",
    "CharField",
    "TextField",
    "IntegerField",
    "BigIntegerField",
    "SmallIntegerField",
    "FloatField",
    "DecimalField",
    "BooleanField",
    "UUIDField",
    "DateField",
    "DateTimeField",
    "TimeField",
    "TimeDeltaField",
    "JSONField",
    "JSONBField",
    "ArrayField",
    "UUIDArrayField",
    "JSONBArrayField",
    "TextArrayField",
    "IntegerArrayField",
    "BooleanArrayField",
    "DecimalArrayField",
    "DateArrayField",
    "TimeArrayField",
    "HStoreArrayField",
    "IPv6ArrayField",
    "IPNetworkArrayField",
    "PrimitiveArrayField",
    "EnumField",
    "IPAddressField",
    "IPv4Field",
    "IPv6Field",
    "IPNetworkField",
    "MacAddressField",
    "HStoreField",
    "PointField",
    "MoneyField",
    "BinaryField",
    "EmailField",
    "SlugField",
    "FileField",
    "ImageField",
    "CITextField",
    "CompositeField",
    "RangeField",
    "VersionField",
    "VectorField",
    # ── Relation fields ────────────────────────────────────────────────────────
    "ForeignKey",
    "ManyToManyField",
    # ── Expressions & Q objects ────────────────────────────────────────────────
    "F",
    "Expression",
    "Q",
    "OuterRef",
    "Subquery",
    "Exists",
    "Func",
    "Aggregate",
    "Coalesce",
    "Lower",
    "Upper",
    "Length",
    "Trim",
    "Now",
    "Concat",
    "Greatest",
    "Least",
    "Abs",
    "Round",
    "Cast",
    "Extract",
    "DateTrunc",
    # ── Aggregate functions ────────────────────────────────────────────────────
    "Sum",
    "Avg",
    "Min",
    "Max",
    "Count",
    "StdDev",
    "Variance",
    # ── Window functions ───────────────────────────────────────────────────────
    "Window",
    "RowNumber",
    "Rank",
    "DenseRank",
    "Lag",
    "Lead",
    "FirstValue",
    "LastValue",
    "NthValue",
    "Ntile",
    "CumeDist",
    "PercentRank",
    # ── CTEs ──────────────────────────────────────────────────────────────────
    "CTE",
    # ── Vector search ─────────────────────────────────────────────────────────
    "VectorDistance",
    "VECTOR_METRICS",
    # ── Pagination ─────────────────────────────────────────────────────────────
    "Paginator",
    "Page",
    # ── Signals ────────────────────────────────────────────────────────────────
    "Signal",
    "pre_create",
    "post_create",
    "pre_save",
    "post_save",
    "pre_delete",
    "post_delete",
    # ── Transactions ───────────────────────────────────────────────────────────
    "transaction",
    # ── Cache ──────────────────────────────────────────────────────────────────
    "CachePolicy",
    "StateManager",
    # ── Exceptions ─────────────────────────────────────────────────────────────
    "ORMException",
    "ValidationError",
    "QueryError",
    "DoesNotExist",
    "MultipleObjectsReturned",
    "DatabaseError",
    "ConnectionError",
    "IntegrityError",
    "TransactionError",
    "ConfigurationError",
    "CacheError",
    "StateError",
    "RelationshipError",
    "AdapterError",
    "FieldError",
    "MigrationError",
    "ParameterError",
    "UnknownDatabaseError",
    "OptimisticLockError",
    # ── Migrations ─────────────────────────────────────────────────────────────
    "MigrationDB",
    "MigrationLoader",
    "MigrationState",
    "MigrationExecutor",
    "DDLGenerator",
    "IndexDef",
    "SchemaDiff",
    "TableFilter",
    "makemigrations",
    "migrate",
    "migration_status",
    "create_empty",
    "rollback",
    "migrate_and_rebuild",
]
